### PR TITLE
App In app survey back navigation and tweaks [sc-7788]

### PR DESCRIPTION
**Pull request by lvancraen**
Story: https://app.shortcut.com/capable/story/7788/app-in-app-survey-back-navigation-and-tweaks

https://user-images.githubusercontent.com/15220513/189411659-f2673cb5-5aca-440c-b864-0fb64905f641.mov

### CODE REVIEW

**Comment by lvancraen** [comment]
@achidu I've added the responses to the end of the survey

https://user-images.githubusercontent.com/15220513/189609917-5487ab67-aac5-4aea-8bfe-82e33cc00f7c.mov

**Comment by achidu** [comment]
> @achidu I've added the responses to the end of the survey. I know it doesn't match the design quite yet. But I'll do that in another PR.
> 
>  Screen.Recording.2022-09-12.at.4.24.04.AM.mov

Looking good! Just created a ticket for the next PR: https://app.shortcut.com/capable/story/7874

**Review by lawyu89 — APPROVED** [review]
LGTM

**Comment by lvancraen** [comment]
Updated completed screen
Screen Shot 2022-09-13 at 2 50 25 AM

**Pull request merged**
