### PR TITLE
Add new font style to make "Member Since" bigger

### PR DESCRIPTION
**Pull request by achidu**
Needed to make the text for the "Member Since" text on the profile page bigger. 

Instead of adding custom styling to the component I created a new font style and swapped it into the variant for that text. Happy to do it differently if we prefer another way.

I added in the new style under two of the typography interfaces, but only because it yelled at me otherwise so hopefully that makes sense.

And ignore the type in the branch name.

### CODE REVIEW

**Comment by achidu** [comment]
Alternatively, we could make the font size for the `small` variant bigger, but I couldn't quickly figure out what else was using it. I think the "Member Since" text used to be bigger, so I'm assuming we changed the `small` font size when making another change previously without realizing this got smaller, too (so I assume we _are_ using it somewhere else).

**Comment by achidu** [comment]
https://app.shortcut.com/capable/story/7915/app-make-memeber-since-text-larger

**Comment by achidu** [comment]
I see this a lot, not sure if it's related to my changes

image

**Review by lawyu89 — APPROVED** [review]
LGTM

**Review by lvancraen — APPROVED** [review]
I don't think those tests are up to date anymore. We'll most likely need to replace them

**Pull request merged**
