### PR TITLE
Display product name and description for subscription plan

### PR DESCRIPTION
**Pull request by lawyu89**
for 
[sc-7811]
Screen Shot 2022-09-08 at 7 57 09 PM

### CODE REVIEW

**Comment by achidu** [comment]
im having trouble testing on my local for some reason 😞 unable to load anything when i add the stripe env variables
but looks good to me from your screenshot 👍

**Comment by lawyu89** [comment]
> im having trouble testing on my local for some reason 😞 unable to load anything when i add the stripe env variables but looks good to me from your screenshot 👍

ya you wont be able to test locally until i merge my backend pr in :D

**Comment by achidu** [comment]
> > im having trouble testing on my local for some reason 😞 unable to load anything when i add the stripe env variables but looks good to me from your screenshot 👍
> 
> ya you wont be able to test locally until i merge my backend pr in :D ([capable-health/barnard#1939](https://github.com/capable-health/barnard/pull/1939))

oh duh 🙃

**Comment by lawyu89** [comment]
> > > im having trouble testing on my local for some reason 😞 unable to load anything when i add the stripe env variables but looks good to me from your screenshot 👍
> > 
> > 
> > ya you wont be able to test locally until i merge my backend pr in :D ([capable-health/barnard#1939](https://github.com/capable-health/barnard/pull/1939))
> 
> oh duh 🙃

both prs have been merged in, feel free to test 😃

**Pull request merged**
